services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - /mine-info-site/pg/pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "54321:5432"
      
  flask:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: flask
    volumes:
      - /mine-info-site/uploads:/app/app/static/uploads
      - /mine-info-site/logs:/app/logs
      - /mine-info-site/pg/migrations:/app/migrations
    env_file:
      - .env
    depends_on:
      - postgres
    expose:
      - 8080

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: nginx
    volumes:
      - /mine-info-site/certs:/etc/nginx/ssl
    env_file:
      - .env
    depends_on:
      - flask
    ports:
      - "80:80"
      - "443:443"
  
