name: Deploy by runner

on:
  push:
    branches: [ "main" ]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: down old containers
        run: echo ${{ secrets.USERPWD }} | sudo docker compose down && echo "Containers stopped" || true
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Start compose
        run: echo ${{ secrets.USERPWD }} | sudo -E POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} docker compose up --build -d
