name: Deploy by runner

on:
  push:
    branches: [ "main" ]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: export db passwd
        run: export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - name: down old containers
        run: sudo docker-compose down
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Start compose
        run: echo ${{ secrets.USERPWD }} | sudo -E docker compose up --build -d
